python: can't open file 'app.py': [Errno 2] No such file or directory
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.[K
remote: error: Trace: 5afec874b0fa0a65c585ecede53aaeb9[K
remote: error: See http://git.io/iEPt8g for more information.[K
remote: error: File main/.nohup.out.swp is 192.36 MB; this exceeds GitHub's file size limit of 100.00 MB[K
To git@github.com:Bunrning-Bear/CloudEye.git
 ! [remote rejected] develop -> develop (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:Bunrning-Bear/CloudEye.git'
